# Задание 1

In [1]:
import numpy as np

data = np.load('./1/matrix_2.npy')
data

array([[423, 884, 647, ..., 925, 644, 291],
       [620, 415, 566, ..., 424, 136, 771],
       [904, 788, 790, ..., 781, 481, 343],
       ...,
       [148, 430, 327, ..., 838, 212, 203],
       [393, 637, 456, ..., 218, 764, 852],
       [749, 803, 953, ..., 387, 106, 705]])

In [2]:
main_diag = np.diag(data)
side_diag = np.diag(np.flip(data, axis=1))
res = {
    'sum': str(np.sum(data)),
    'avr': str(np.mean(data)), 
    'sumMD': str(np.sum(main_diag)),  
    'avrMD': str(np.mean(main_diag)), 
    'sumSD': str(np.sum(side_diag)),  
    'avrSD': str(np.mean(side_diag)), 
    'max': str(np.max(data)), 
    'min': str(np.min(data)) 
}

In [3]:
import json
with open("1_stats.json", "w") as outfile: 
    json.dump(res, outfile)

In [4]:
data = (data - float(res['min'])) / (float(res['max']) - float(res['min']))
np.save("1.npy", data)

# Задание 2

In [5]:
data = np.load('./2/matrix_2_2.npy')
data

array([[ 719, 1019,  307, ..., 1020, 1438,  202],
       [ 658,  574,  288, ...,  695,  366, 1030],
       [1294, 1016,  664, ...,  846, 1203,  484],
       ...,
       [ 436,  279,  389, ...,  864,  106, 1015],
       [ 780,  352, 1297, ...,  910, 1135,  920],
       [1382,  740,  365, ..., 1188, 1454,  919]])

In [6]:
xyz = np.array([(i % data.shape[1], i // data.shape[1], data[i//data.shape[1], i%data.shape[1]]) 
                for i in range(data.shape[0] * data.shape[1]) if data[i//data.shape[1], i%data.shape[1]] > 500+2])
xyz

array([[   0,    0,  719],
       [   1,    0, 1019],
       [   3,    0,  973],
       ...,
       [ 385,  387, 1188],
       [ 386,  387, 1454],
       [ 387,  387,  919]])

In [7]:
np.savez("2.npz", data)
np.savez_compressed("2_compressed.npz", data)

In [8]:
print(f'Разница: {602440 - 282624} байт, {int(round((602440 - 282624) / 602440, 2) * 100)}%')

Разница: 319816 байт, 53%


# Задание 3

In [9]:
import json

with open('./3/products_2.json', 'r') as f:
    data = json.load(f)

In [10]:
products = {}
for e in data:
    if e['name'] in products:
        products[e['name']].append(e['price'])
    else:
        products[e['name']] = [e['price']]


In [11]:
statistics = {}
for i, product in enumerate(products):
    statistics[product] = {
        'avg': str(np.mean(products[product])), 
        'max': str(np.max(products[product])),
        'min': str(np.min(products[product]))
    }
statistics

{'Peach': {'avg': '54.7563870967742', 'max': '99.31', 'min': '5.07'},
 'Apple': {'avg': '54.32467479674796', 'max': '99.78', 'min': '5.07'},
 'Banana': {'avg': '50.80389521640091', 'max': '99.69', 'min': '5.28'},
 'Mango': {'avg': '52.85378021978022', 'max': '99.62', 'min': '5.14'},
 'Guava': {'avg': '52.20596673596673', 'max': '99.82', 'min': '5.34'},
 'Kiwifruit': {'avg': '52.93342857142857', 'max': '99.82', 'min': '5.52'},
 'Raspberry': {'avg': '51.88988839285714', 'max': '99.89', 'min': '5.09'},
 'Strawberry': {'avg': '54.407120535714284', 'max': '99.83', 'min': '5.41'},
 'Grapes': {'avg': '51.60929046563193', 'max': '100.0', 'min': '5.0'},
 'Cranberry': {'avg': '54.38699774266366', 'max': '99.95', 'min': '5.79'},
 'Pineapple': {'avg': '51.56455399061033', 'max': '100.0', 'min': '5.0'},
 'Cherry': {'avg': '51.47675', 'max': '99.72', 'min': '5.06'},
 'Apricot': {'avg': '51.593963963963965', 'max': '99.82', 'min': '5.08'},
 'Orange': {'avg': '49.137192224622034', 'max': '99.91', 'min

In [12]:
import msgpack

with open("3_stats.json", "w") as outfile: 
    json.dump(res, outfile)

with open("3_stats.msgpack", "wb") as outfile:
    packed = msgpack.packb(statistics)
    outfile.write(packed)

In [13]:
print(f'Разница: {997 - 150} байт, {int(round((997 - 150) / 997, 2) * 100)}%, .json весит сильно меньше')

Разница: 847 байт, 85%, .json весит сильно меньше


# Задание 4

In [14]:
import pickle

with open("4/products_2.pkl", "rb") as f:
    products = pickle.load(f)

with open("4/price_info_2.json") as f:
    price_info = json.load(f)

In [15]:
for i in range(len(products)):
    name, price = products[i]['name'], products[i]['price']
    _, method, param = list(filter(lambda x: x['name'] == name, price_info))[0].values()
    if method == 'sum':
        products[i]['price'] = price + param
    elif method == 'sub':
        products[i]['price'] = price - param
    elif method == 'percent+':        
        products[i]['price'] = price * (1 + param)
    elif method == 'percent-':        
        products[i]['price'] = price * (1 - param)

with open('4.pickle', 'wb') as f:
    pickle.dump(products, f)

# Задание 5

In [16]:
import pandas as pd

# https://www.kaggle.com/datasets/manjitbaishya001/la-crime-data-2010-to-2023
df = pd.read_csv('la_crime_2010_to_2023.csv')
df.head()

DR_NO               Date Rptd                DATE OCC  TIME OCC  AREA   \
0    1307355  02/20/2010 12:00:00 AM  02/20/2010 12:00:00 AM      1350   13.0   
1   11401303  09/13/2010 12:00:00 AM  09/12/2010 12:00:00 AM        45   14.0   
2   70309629  08/09/2010 12:00:00 AM  08/09/2010 12:00:00 AM      1515   13.0   
3   90631215  01/05/2010 12:00:00 AM  01/05/2010 12:00:00 AM       150    6.0   
4  100100501  01/03/2010 12:00:00 AM  01/02/2010 12:00:00 AM      2100    1.0   

   AREA NAME  Rpt Dist No  Part 1-2  Crm Cd  \
0     Newton         1385         2     900   
1    Pacific         1485         2     740   
2     Newton         1324         2     946   
3  Hollywood          646         2     900   
4    Central          176         1     122   

                                         Crm Cd Desc  ...   Status Desc  \
0                           VIOLATION OF COURT ORDER  ...  Adult Arrest   
1  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...  ...   Invest Cont   
2                          OTHER MISCELLANEOUS CRIME  ...   Invest Cont   
3                           VIOLATION OF COURT ORDER  ...   Invest Cont   
4                                    RAPE, ATTEMPTED  ...   Invest Cont   

   Crm Cd 1 Crm Cd 2 Crm Cd 3  Crm Cd 4  \
0     900.0      NaN      NaN       NaN   
1     740.0      NaN      NaN       NaN   
2     946.0      NaN      NaN       NaN   
3     900.0    998.0      NaN       NaN   
4     122.0      NaN      NaN       NaN   

                                  LOCATION                     Cross Street  \
0   300 E  GAGE                         AV                              NaN   
1          SEPULVEDA                    BL  MANCHESTER                   AV   
2  1300 E  21ST                         ST                              NaN   
3          CAHUENGA                     BL  HOLLYWOOD                    BL   
4          8TH                          ST  SAN PEDRO                    ST   

       LAT       LON AREA  
0  33.9825 -118.2695  NaN  
1  33.9599 -118.3962  NaN  
2  34.0224 -118.2524  NaN  
3  34.1016 -118.3295  NaN  
4  34.0387 -118.2488  NaN  

[5 rows x 29 columns]

In [17]:
data = df[['AREA', 'AREA NAME', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Status Desc', 'LAT', 'LON']].dropna()
data


AREA    AREA NAME  Part 1-2  Crm Cd  \
2135775   3.0    Southwest         2     624   
2135776   1.0      Central         2     624   
2135777   1.0      Central         2     845   
2135778  15.0  N Hollywood         2     745   
2135779  19.0      Mission         2     740   
...       ...          ...       ...     ...   
2993428  16.0     Foothill         1     230   
2993429  12.0  77th Street         1     230   
2993430   1.0      Central         1     352   
2993431   9.0     Van Nuys         2     745   
2993432   3.0    Southwest         1     331   

                                               Crm Cd Desc   Status Desc  \
2135775                           BATTERY - SIMPLE ASSAULT   Adult Other   
2135776                           BATTERY - SIMPLE ASSAULT   Invest Cont   
2135777          SEX OFFENDER REGISTRANT OUT OF COMPLIANCE  Adult Arrest   
2135778           VANDALISM - MISDEAMEANOR ($399 OR UNDER)   Invest Cont   
2135779  VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...   Invest Cont   
...                                                    ...           ...   
2993428     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT   Invest Cont   
2993429     ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT   Invest Cont   
2993430                                         PICKPOCKET   Invest Cont   
2993431           VANDALISM - MISDEAMEANOR ($399 OR UNDER)   Invest Cont   
2993432  THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...   Invest Cont   

             LAT       LON  
2135775  34.0141 -118.2978  
2135776  34.0459 -118.2545  
2135777  34.0448 -118.2474  
2135778  34.1685 -118.4019  
2135779  34.2198 -118.4468  
...          ...       ...  
2993428  34.2790 -118.4116  
2993429  33.9841 -118.2915  
2993430  34.0467 -118.2485  
2993431  34.1951 -118.4487  
2993432  34.0091 -118.3078  

[857658 rows x 8 columns]

In [18]:
stats = {}
for category in data.columns:
    if data[category].dtype != 'object':
        stats[category] = {
            'min': str(np.min(data[category])),
            'max': str(np.max(data[category])),  
            'mean': str(np.mean(data[category])),        
            'sum': str(np.sum(data[category])),    
            'std': str(np.std(data[category]))
        }
    else:
        stats[category] = {e[0]: str(e[1]) for e in tuple(zip(*np.unique(data['AREA NAME'], return_counts=True)))}

with open("5_stats.json", "w") as outfile: 
    json.dump(stats, outfile)

In [19]:
data.to_csv('5.csv', index=False)

data.to_json('5.json')

data.to_pickle('5.pickle')

with open("5.msgpack", "wb") as outfile:
    packed = msgpack.packb(data.to_dict())
    outfile.write(packed)

In [20]:
print(f'Размеры: \ncsv: \t\t68 019 КБ\njson: \t\t138 902 КБ\npickle: \t51 945 КБ\nmsgpack: \t102 886 КБ')

Размеры: 
csv: 		68 019 КБ
json: 		138 902 КБ
pickle: 	51 945 КБ
msgpack: 	102 886 КБ
